export const formFields = {
    "lead-id": "35",
    "is-married": "1",
    "presentation-script-select": "cskw",
    "tobacco-question": "on",
    "plan-type": "alx-head-start-plan",
    "alx-head-start-final-expense": "Yes",
    "alx-head-start-final-expense-existing-coverage": "5000",
    "alx-head-start-final-expense-amount-needed": "30000",
    "alx-head-start-final-expense-qualified-amount": "30000",
    "spouse-alx-head-start-final-expense": "No",
    "spouse-alx-head-start-final-expense-existing-coverage": "",
    "spouse-alx-head-start-final-expense-amount-needed": "",
    "spouse-alx-head-start-final-expense-qualified-amount": "",
    "head-start-child[0][child-name]": "TK",
    "head-start-child[0][policy-amount]": "5000",
    "accident-protector-max-radio": "Yes",
    "acb-accident-radio": "Yes",
    "critical-illness-protection": "No",
    "cash-cancer": "No",
    "cancer-endurance": "No",
    "intensive-care": "No",
    "option-1": "125.78",
    "option-2": "120.15",
    "has-rebuttals": "No",
    "down-closing-radio": "No"
};